language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - pip install .
  - pip install -r requirements.txt

before_script:
    - wget http://www.tcpdump.org/release/libpcap-1.7.2.tar.gz && tar xvf libpcap-1.7.2.tar.gz

script: nosetests
